name: test

on:
  push:
  pull_request:
    types: [review_requested, ready_for_review]

jobs:
  # *************************************
  # ************* Pre-commit ************
  # *************************************
  pre-commit:
    name: pre-commit ${{ matrix.python-version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      max-parallel: 5
      matrix:
        os:
          - ubuntu-22.04
        python-version:
          - "3.11"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
      - name: Install pre-commit requirements
        run: pip install --no-cache-dir detect-secrets doc8 isort
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

  # *************************************
  # ************* Main tests ************
  # *************************************
  test:
    needs: pre-commit
    name: test ${{ matrix.python-version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        os:
          - ubuntu-22.04
        python-version:
          - "3.11"
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    - name: Install dependencies
      run: python -m pip install --no-cache-dir -e .[all]
    - name: Run test suite
      run: pytest -vrx -s
      env:
        PYTEST_ADDOPTS: "--durations=10"
